# We require "sudo" since we're running a docker container.
# See: https://docs.travis-ci.com/user/docker/
sudo: required
services:
  - docker

language: python

# This should match the version run by tox.
python:
  - "2.7"

env:
  global:
    - DJANGO_DB_ENGINE=django.db.backends.postgresql
    - DJANGO_DB_NAME=postgres
    - DJANGO_DB_HOST=localhost
    - DJANGO_DB_USER=postgres
    - DJANGO_DB_PASSWORD=mysecret

script:
  - docker-compose up tox
